#+TITLE: Doom Emacs Configuration

Literate and modular Doom Emacs configuration.

* Table of contents :TOC:
- [[#about][About]]
- [[#tangle][Tangle]]
- [[#helpers][Helpers]]
  - [[#predefined][Predefined]]
  - [[#windows-librewolf-in-wsl][Windows =Librewolf= in wsl]]
  - [[#shortcuts][Shortcuts]]
  - [[#window][Window]]
  - [[#ediff][ediff]]
- [[#input][Input]]
  - [[#chinese][Chinese]]
- [[#completion][Completion]]
  - [[#corfu][corfu]]
  - [[#vertico][vertico]]
- [[#ui][UI]]
  - [[#extra-themes][Extra themes]]
  - [[#doom][doom]]
  - [[#doom-dashboard][doom-dashboard]]
  - [[#modeline][modeline]]
  - [[#popup][popup]]
  - [[#unicode][unicode]]
  - [[#rainbow-mode][rainbow-mode]]
  - [[#workspace][Workspace]]
  - [[#others][Others]]
- [[#editor][Editor]]
  - [[#whitespace][whitespace]]
  - [[#parinfer][parinfer]]
  - [[#evil][evil]]
  - [[#snippets][snippets]]
  - [[#fold][fold]]
  - [[#undo][Undo]]
  - [[#unfill][unfill]]
- [[#emacs][Emacs]]
  - [[#dired][dired]]
  - [[#dirvish][dirvish]]
  - [[#tramp][tramp]]
  - [[#proxy][proxy]]
- [[#term][Term]]
  - [[#navigation][Navigation]]
  - [[#vterm][vterm]]
  - [[#ghostel][ghostel]]
- [[#checkers][Checkers]]
  - [[#spell-checker][Spell checker]]
- [[#tools][Tools]]
  - [[#lookup][lookup]]
  - [[#llm][llm]]
  - [[#agent][agent]]
  - [[#mcp-server][MCP server]]
  - [[#magit][magit]]
  - [[#transient][transient]]
  - [[#pdf][pdf]]
  - [[#go-translate][go-translate]]
  - [[#pacdiff][pacdiff]]
  - [[#tldr][tldr]]
- [[#lang][Lang]]
  - [[#latex][Latex]]
  - [[#lua][lua]]
  - [[#org][org]]
  - [[#python][python]]
  - [[#sh][sh]]
  - [[#yaml][yaml]]
  - [[#wolfram][wolfram]]
  - [[#typst][typst]]
  - [[#kdl][kdl]]
- [[#email][Email]]
  - [[#mu4e][mu4e]]
- [[#app][App]]
  - [[#rss][rss]]
  - [[#everywhere][everywhere]]
  - [[#screenshot][screenshot]]

* About
The *conventions* of this org file:
- First level heading respect Doom's order

- Configured module goes to second level heading ::
  - Prerequisite packages tangled into [[file:packages.toml]] (=Arch= only)

  - Bootstrap scripts tangled to [[file:install.d/]]

  - Comment a module with [[kbd:][C-c ;]] at heading

- One line config goes into [[* Tangle]] ::
  Often a declare in [[file:init.el]]

* Tangle
[[file:init.el]]
#+begin_src emacs-lisp :tangle init.el :noweb tangle :shebang ";;; init.el -*- lexical-binding: t; -*-\n"
(doom!
 :input
 <<input>>

 :completion
 <<completion>>

 :ui
 <<ui>>
 hl-todo
 indent-guides
 (ligatures +extra)
 nav-flash
 ophints
 smooth-scroll
 (vc-gutter +pretty)
 (window-select +numbers)
 workspaces
 ;zen

 :editor
 <<editor>>
 format
 ;file-templates
 ;multiple-cursors
 parinfer
 word-wrap

 :emacs
 <<emacs>>
 ;electric
 ;ibuffer
 undo
 vc

 :term
 <<term>>

 :checkers
 <<checkers>>
 (syntax +childframe)

 :tools
 <<tools>>
 (lsp +eglot)
 biblio
 debugger
 ;editorconfig
 (eval +overlay)
 tree-sitter
 ;upload

 :os
 ;tty

 :lang
 markdown
 <<lang>>
 ;(cc +lsp)
 emacs-lisp
 json

 :email
 <<email>>

 :app
 calendar
 <<app>>

 :config
 literate
 (default +bindings +smartparens))
#+end_src
*The order of modules in above list make sense*

Extra packages from [[https://melpa.org][MELPA]]
#+begin_src emacs-lisp :tangle packages.el :shebang ";; -*- no-byte-compile: t; -*-"
#+end_src

#+PROPERTY: header-args:emacs-lisp :results none
Default tangle to [[file:config.el]]
#+begin_src emacs-lisp :shebang ";;; $DOOMDIR/config.el -*- lexical-binding: t; -*-\n" :noweb tangle
(load (expand-file-name "private/identity.el" doom-user-dir) nil 'nomessage)

<<predefines>>
#+end_src

Default install all packages in [[file:packages.toml]]
#+PROPERTY: header-args:toml :tangle packages.toml
#+begin_src toml
enable_default=true
#+end_src

* Helpers
** Predefined
:PROPERTIES:
:header-args:emacs-lisp: :noweb-ref predefines
:END:

#+begin_src emacs-lisp
(defun +my/is-utility-daemon ()
  "If current session run from daemon called `utility`."
  (equal (daemonp) "utility"))
#+end_src

** Windows =Librewolf= in wsl
Open link with host =Librewolf= browser
#+begin_src emacs-lisp
(if (featurep :system 'wsl)
  (setq browse-url-firefox-program "librewolf.exe"))
#+end_src

** Shortcuts
#+begin_src emacs-lisp
(map! :leader
      :desc "Eval expression"       ":"    #'pp-eval-expression
      :desc "M-x"                   ";"    #'execute-extended-command)
#+end_src

** Window
#+begin_src emacs-lisp
(defun +my/ace-swap-buffer-keep-focus ()
  "Swap current window's buffer with ace-selected window, keep cursor here."
  (interactive)
  (require 'ace-window)
  (let ((cur-win (selected-window))
        (cur-buf (current-buffer)))
    (aw-select " Ace - Swap Buffer"
               (lambda (win)
                 (set-window-buffer cur-win (window-buffer win))
                 (set-window-buffer win cur-buf)))))

(map! :leader :prefix "w"
      :desc "Swap buffer keep focus" "X" #'+my/ace-swap-buffer-keep-focus)
#+end_src

** ediff
#+begin_src emacs-lisp
(add-hook 'ediff-prepare-buffer-hook
          (lambda ()
            (+word-wrap-mode 1)
            (when (derived-mode-p 'org-mode)
              (org-fold-show-all))))
#+end_src

** COMMENT Backup

#+begin_src emacs-lisp
(defun +my/corfu-add-cape-dabbrev-h ()
  (add-hook 'completion-at-point-functions #'cape-dabbrev 90 t))
(advice-add '+corfu-add-cape-dabbrev-h :override #'+my/corfu-add-cape-dabbrev-h)
;; (advice-remove '+corfu-add-cape-dabbrev-h #'+my/corfu-add-cape-dabbrev-h)
#+end_src

No reason to scale super/sub-script down!
#+begin_src emacs-lisp
(after! 'font-latex
  (set-face-attribute 'font-latex-superscript-face nil :height 'unspecified)
  (set-face-attribute 'font-latex-subscript-face nil :height 'unspecified))
#+end_src

* Input
** Chinese
#+begin_src toml
[chinese]
packages=["base-devel",
    "librime" # for +rime
]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref input :noweb yes
(chinese<<chinese-flags()>>)
#+end_src

#+NAME: chinese-flags
#+BEGIN_SRC emacs-lisp :results value :exports none :tangle no
(if (featurep :system 'wsl)
    " +rime +childframe" "")
#+END_SRC

Default simplified Chinese input
#+begin_src emacs-lisp
(after! liberime
  (liberime-try-select-schema "luna_pinyin_simp")
  (setq pyim-default-scheme 'rime-quanpin))
#+end_src

This is useful for allowing breaking after CJK characters and improves the
word-wrapping for CJK text mixed with Latin text.
#+begin_src emacs-lisp
(setq word-wrap-by-category t)
#+end_src

*** cns
[[https://github.com/kanglmf/emacs-chinese-word-segmentation][GitHub - kanglmf/emacs-chinese-word-segmentation]]

[[https://github.com/kanglmf/emacs-chinese-word-segmentation/issues/7][kanglmf/emacs-chinese-word-segmentation#7]]
#+begin_src emacs-lisp :tangle packages.el
(package! cns
  :recipe (:host github :repo "kanglmf/emacs-chinese-word-segmentation"
           :pre-build ("make")
           :files ("*.el" "cnws" "cppjieba/dict")))
#+end_src

#+begin_src emacs-lisp
(use-package! cns
  :commands (cns-mode global-cns-mode cns-auto-enable)
  :config
  (defvar cns-packages-path
    (expand-file-name (format "straight/build-%s/cns" emacs-version) doom-local-dir))
  (setq cns-process-type 'shell
        cns-prog (expand-file-name "cnws" cns-packages-path)
        cns-dict-directory (expand-file-name "dict" cns-packages-path))
  :hook
  (find-file . cns-auto-enable))
#+end_src

* Completion
** corfu
#+begin_src toml
[corfu]
packages=["words"]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref completion
(corfu +icons +dabbrev)
#+end_src

#+begin_src emacs-lisp
(setq corfu-on-exact-match 'show)
(map! :after cape :i "C-c p" cape-prefix-map)

;; dabb_ only match dabbrev not Dabbrev!
(after! dabbrev
  (setq dabbrev-case-fold-search nil))
#+end_src

** vertico
#+begin_src emacs-lisp :tangle no :noweb-ref completion
(vertico +icons +childframe)
#+end_src

[[https://github.com/tumashu/vertico-posframe/issues/16][tumashu/vertico-posframe#16 Disable vertico-posframe when Emacs runs in terminal]]
#+begin_src emacs-lisp
(after! vertico-multiform
  (add-to-list 'vertico-multiform-commands
               '(consult-line
                 posframe
                 (vertico-posframe-fallback-mode . vertico-buffer-mode))))
#+end_src

#+begin_src emacs-lisp
(after! vertico-posframe
  (setq vertico-posframe-width 88))
#+end_src

* UI
** Extra themes
#+begin_src emacs-lisp :tangle packages.el
(package! ewal-doom-themes)
#+end_src

#+begin_src emacs-lisp
(use-package! ewal-doom-themes)
#+end_src

load wal theme from command line
#+begin_src fish :tangle no
emacs-client -e "(load-theme 'ewal-doom-themes t)"
#+end_src

[[https://github.com/donniebreve/rose-pine-doom-emacs][GitHub - donniebreve/rose-pine-doom-emacs: Soho vibes for DOOM Emacs]]

** doom
#+begin_src emacs-lisp :tangle no :noweb-ref ui
doom
#+end_src

*** Themes
restore last selected theme
#+begin_src emacs-lisp
(defun load-in-doom-dir (file-name &optional dir)
  (let* ((dir (or dir doom-user-dir))
         (full-name (expand-file-name file-name dir)))
    (if (file-exists-p full-name)
        (load full-name))))

(load-in-doom-dir "theme.el" doom-cache-dir)
#+end_src

difficult to choose theme? random it
#+begin_src emacs-lisp
(defun +my/random-theme ()
  (interactive)
  (let* ((all-themes (custom-available-themes))
         (next-theme (nth (random (length all-themes)) all-themes)))
    (consult-theme next-theme)
    (message (format "switch to theme: %s" next-theme))))

(map! :leader
      (:prefix "t"
       :desc "Random theme" "t" #'+my/random-theme))
#+end_src

track current theme for later load
#+begin_src emacs-lisp
(defun +my/save-theme (prev new-theme &rest args)
  (let
      ((theme-config-file (expand-file-name "theme.el" doom-cache-dir)))
    (write-region
     (format "(setq doom-theme '%s)\n" new-theme) nil theme-config-file)
    (message "Switch to theme: %s" new-theme)))

(add-variable-watcher 'doom-theme #'+my/save-theme)
#+end_src

*** Fonts
*bold* /italic/ _underline_ +stride+

Set default font size, =WSL= currently not aware dpi settings in
[[file:~/.Xresources]] while float size makes it work on Linux.

- [[https://github.com/doomemacs/doomemacs/issues/6131][doomemacs/doomemacs#6131 DPI settings are not respected by "setq doom-font"]]
- [[https://github.com/doomemacs/doomemacs/blob/master/docs/faq.org#change-my-fonts][Change my fonts - doom/docs/faq]]

#+begin_src emacs-lisp
(setq +my/font-size (* (if (featurep :system 'wsl) 1.5 1) 12.0))

(setq doom-font (font-spec :family "Maple6 NF" :size +my/font-size))
#+end_src

#+begin_src emacs-lisp
(add-hook 'doom-load-theme-hook
  (lambda ()
    ;; quoted text in info
    (set-face-attribute 'fixed-pitch-serif nil :slant 'italic :foreground "tomato")
    ;; prefer italic comment font
    (set-face-attribute 'font-lock-comment-face nil :slant 'italic)))
#+end_src

** doom-dashboard
#+begin_src emacs-lisp :tangle no :noweb-ref ui
dashboard
#+end_src

- [[https://discourse.doomemacs.org/t/how-to-change-your-splash-screen/57][How to change your splash screen - Configuration - Doom Emacs Discourse]]

#+begin_src emacs-lisp
(setq fancy-splash-image (expand-file-name "assets/bitmap_512x.png" doom-user-dir))
#+end_src

** modeline
#+begin_src toml
[modeline]
packages=["otf-comicshanns-nerd"]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref ui
modeline
#+end_src

custom doom-modeline font, valid on startup and persist after [[cmd:doom/reload-theme]]
#+begin_src emacs-lisp
(defun +my/set-mode-line-font ()
  (set-face-font 'mode-line (font-spec :family "ComicShannsMono Nerd Font" :size (+ +my/font-size 1.5)))
  (set-face-font 'mode-line-inactive (font-spec :family "ComicShannsMono Nerd Font" :size (+ +my/font-size 1.5))))

(add-hook 'doom-load-theme-hook #'+my/set-mode-line-font 90)
#+end_src

*** keycast
#+begin_src emacs-lisp :tangle packages.el
(package! keycast)
#+end_src

[[https://github.com/tarsius/keycast/issues/7#issuecomment-881469067][tarsius/keycast#7 Add support for moody and doom-modeline.]]
#+begin_src emacs-lisp
(use-package! keycast
  :commands (keycast-mode)
  :init
  (map! :leader
        (:prefix "t"
         :desc "Toggle keycast" "k" #'keycast-mode))
  :config
  (define-minor-mode keycast-mode
    "Show current command and its key binding in the mode line (fix for use with doom-mode-line)."
    :global t
    (if keycast-mode
        (progn (add-hook 'pre-command-hook 'keycast--update t)
               (setq keycast-mode-line-window-predicate
                     'keycast-active-frame-bottom-right-p))
     (remove-hook 'pre-command-hook 'keycast--update)
     (setq keycast-mode-line-window-predicate 'ignore)))
  (add-to-list 'global-mode-string '("" keycast-mode-line)))
#+end_src

** popup
#+begin_src emacs-lisp :tangle no :noweb-ref ui
(popup +defaults)
#+end_src

#+begin_src emacs-lisp
(setq split-width-threshold 120)
#+end_src

Prefer stack at right for following info windows, since they are fill-columned
#+begin_src emacs-lisp
(set-popup-rules!
  '(("^\\*\\([Hh]elp\\|Apropos\\)"  ; help messages
     :side right :size 80 :slot 2 :vslot -8 :select t)
    ("^\\*\\(?:Wo\\)?Man "
     :side right :size 80 :vslot -6 :select t)
    ("^\\*info\\*$"
     :side right :size 80 :slot 2 :vslot 2 :select t)))
#+end_src

** unicode
#+begin_src toml
[unicode]
packages=[
    "ttf-symbola",          # required by doom
    "quivira",              # org ellipsis ⤵, ℤ
    "ttf-dejavu",           # org heading ◉ ✸ ∈
    "ttf-sarasa_ui-sc", # ￢
    "noto-fonts-emoji",     # color emoji
    "ttf-nerd-fonts-symbols-mono" # nerd font
]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref ui
unicode
#+end_src

*** change font by block
To get unicode block name for a character, [[kbd:SPC h ']] on it to get it's lexical
code, and search in [[https://en.wikipedia.org/wiki/Plane_(Unicode)][Plane (Unicode) - Wikipedia]]

Doom's way of change unicode font, but it will be shadowed by
[[fn:doom-init-fonts-h]] if [[var:doom-symbol-font]] is set.
#+begin_src emacs-lisp
(after! unicode-fonts
  ;; ℕ, ⤵, 𝔹
  (dolist (unicode-block '("Letterlike Symbols" "Supplemental Arrows-B" "Mathematical Alphanumeric Symbols"))
    (push "Quivira" (cadr (assoc unicode-block unicode-fonts-block-font-mapping))))
  ;; ⨂
  (dolist (unicode-block '("Supplemental Mathematical Operators"))
    (push "DejaVu Math TeX Gyre" (cadr (assoc unicode-block unicode-fonts-block-font-mapping))))
  ;; ∈ ∅
  (dolist (unicode-block '("Mathematical Operators"))
    (push "DejaVu Sans" (cadr (assoc unicode-block unicode-fonts-block-font-mapping))))
  ;; ￢
  (dolist (unicode-block '("Halfwidth and Fullwidth Forms"))
    (push "Sarasa UI SC" (cadr (assoc unicode-block unicode-fonts-block-font-mapping)))))
#+end_src

Add to [[var:after-setting-font-hook]] not work well, font display diffs after
[[cmd:doom/reload-theme]]
#+begin_src emacs-lisp :tangle no
(defun +my/unicode-fonts ()
  (dolist (unicode-block '("Letterlike Symbols" "Supplemental Arrows-B"))
    (push "Quivira" (cadr (assoc unicode-block unicode-fonts-block-font-mapping)))))
(add-hook 'after-setting-font-hook #'+my/unicode-fonts 60)
#+end_src

Add hook but with [[fn:set-fontset-font]] succeed
#+begin_src emacs-lisp :tangle no
(defun +my/unicode-fonts ()
  ; Supplemental Arrows-B, include ⤵
  (set-fontset-font t '(#x2900 . #x297f) "Quivira")
  ; Mathematical symbols, 𝔹
  (set-fontset-font t '(#x1d400 . #x1d7ff) "Quivira")
  ; Mathematical operators, ⨂
  (set-fontset-font t '(#x2208 . #x22ff) "DejaVu Math TeX Gyre")
  (dolist (chars '("￢")) ; keywords =not= in code ligatures
     (set-fontset-font t (string-to-char chars) "Sarasa Gothic SC")))
(add-hook 'after-setting-font-hook #'+my/unicode-fonts 60)
#+end_src
see more in [[https://idiocy.org/emacs-fonts-and-fontsets.html][Emacs, fonts and fontsets]]

*** Chinese fonts
[[https://rongcuid.github.io/posts/2021-04-02-Doom-Emacs-CJK.html][Rongcui Dong's Site - 如何在 Doom Emacs 中设置中文]]

Check alignment between Chinese and English.
#+begin_src python :tangle no
Emacs is the advanced, extensible, customizable, self-documenting editor.
# Emacs is the advanced, extensible, customizable, self-documenting editor.
Emacs 是一款可扩展可自定义且自带文档的高级 editor.
#+end_src

These settings will not work in daemon mode if added instead to
=doom-init-ui-hook=, as they might be overridden by =unicode-fonts-setup=.
Additionally, consider changing the font for all =fontset= instead of just
~(frame-parameter nil 'font)~. If the emoji font is not set here, you will need
to use =doom/reload-font= later to enable proper color emoji display.

- [[https://github.com/hick/emacs-chinese#org-的中文问题][GitHub - hick/emacs-chinese: Emacs 相关中文问题以及解决方案]]
- [[https://emacs.stackexchange.com/questions/62219/how-do-i-get-colour-emoji-to-display-in-emacs][fonts - How do I get colour emoji to display in Emacs - Emacs Stack Exchange]]

#+begin_src emacs-lisp
(defun +my/cjk-font ()
  (dolist (charset '(kana han cjk-misc bopomofo))
    (set-fontset-font t charset
                      (font-spec :family "Maple6 SC NF")))
  ;; why not set color emoji font at the same time
  (set-fontset-font t 'emoji "Noto Color Emoji"))

(add-hook 'after-setting-font-hook #'+my/cjk-font)
#+end_src

** rainbow-mode
#+begin_src emacs-lisp :tangle packages.el
(package! rainbow-mode)
#+end_src

** Workspace
#+begin_src emacs-lisp
(defun +my/kill-emacs-without-persp-save ()
  "Kill Emacs without saving perspectives."
  (interactive)
  (let ((persp-auto-save-opt 0)
        (confirm-kill-emacs nil))
    (save-buffers-kill-emacs t)))

(map! :leader
      :desc "Kill Emacs (no persp save)"
      :prefix "q"
      "Q" #'+my/kill-emacs-without-persp-save)
#+end_src

*** projectile
[[https://docs.projectile.mx/projectile/configuration.html][Configuration :: Projectile]]
#+begin_src emacs-lisp
(after! projectile
  (add-to-list 'projectile-globally-ignored-directories
               "*\\.run\\.tmp$")
  (dolist (m '("helpful-mode" "dired-mode"))
    (cl-pushnew m projectile-globally-ignored-modes :test #'equal))
  ;; why I have a mass of projects
  (setq projectile-track-known-projects-automatically nil)
  (add-to-list 'projectile-globally-ignored-buffers "*doom*")
  ;; Prefer .git over .projectile so nested git repos are recognized correctly
  (setq projectile-project-root-functions
        '(projectile-root-local
          projectile-root-bottom-up
          projectile-root-marked
          projectile-root-top-down
          projectile-root-top-down-recurring)))
#+end_src

For non git project, better add following in project root [[file:.dir-locals.el]]
- [[https://emacs.stackexchange.com/questions/16497/how-to-exclude-files-from-projectile][How to exclude files from Projectile? - Emacs Stack Exchange]]
#+begin_src emacs-lisp :tangle no
((nil . ((projectile-indexing-method . hybrid))))
#+end_src
and add ignored files in [[file:.projectile]].

** Others
#+begin_src emacs-lisp
(after! nerd-icons
  (setq nerd-icons-scale-factor 0.9))
#+end_src

Transparency
#+begin_src emacs-lisp
(defun my/toggle-transparency ()
  "Toggle between opaque and semi-transparent frame."
  (interactive)
  (let* ((opaque 100)
         (transparent 92)
         (cur (or (frame-parameter nil 'alpha-background) opaque))
         (new (if (= cur opaque) transparent opaque)))
    (dolist (frame (frame-list))
      (set-frame-parameter frame 'alpha-background new))
    (setf (alist-get 'alpha-background default-frame-alist) new)))

(map! :leader
      (:prefix "t"
       :desc "Toggle transparency" "T" #'my/toggle-transparency))

(my/toggle-transparency)
#+end_src

Line numbers
#+begin_src emacs-lisp
(setq display-line-numbers-type nil)
#+end_src

* Editor
** whitespace
#+begin_src emacs-lisp :tangle no :noweb-ref editor
(whitespace +guess +trim)
#+end_src

** parinfer
#+begin_src emacs-lisp :tangle no
(with-eval-after-load 'parinfer-rust-mode
  (setq parinfer-rust-check-before-enable nil))
#+end_src

** evil
#+begin_src emacs-lisp :tangle no :noweb-ref editor
(evil +everywhere)
#+end_src

#+begin_src emacs-lisp :tangle packages.el
(package! evil-textobj-tree-sitter
  :recipe (:host github :repo "meain/evil-textobj-tree-sitter"))
#+end_src

#+begin_src emacs-lisp
(after! evil
  (setq evil-kill-on-visual-paste nil)
  ;; Disabling cursor movement when exiting insert mode
  (setq evil-move-cursor-back nil)
  ;; keep previous layout, always!
  (setq evil-auto-balance-windows nil))
#+end_src

#+begin_src emacs-lisp
(defvar my/evil-textobj-call-queries
  '((python-mode . ((call arguments: (argument_list) @call.inner)
                    (call) @call.outer))
    (python-ts-mode . ((call arguments: (argument_list) @call.inner)
                       (call) @call.outer))))
#+end_src

#+begin_src emacs-lisp
(use-package! evil-textobj-tree-sitter
  :after evil
  :config
  (define-key evil-inner-text-objects-map "F"
              (evil-textobj-tree-sitter-get-textobj "call.inner"
                                                    my/evil-textobj-call-queries))
  (define-key evil-outer-text-objects-map "F"
              (evil-textobj-tree-sitter-get-textobj "call.outer"
                                                    my/evil-textobj-call-queries)))
#+end_src

#+begin_src emacs-lisp
(after! evil-surround
  ;; I want surround (..), not ( .. )
  (evil--add-to-alist
   evil-surround-pairs-alist
   ?\( '("(" . ")")
   ?\[ '("[" . "]")
   ?\{ '("{" . "}")
   ?\) '("( " . " )")
   ?\] '("[ " . " ]")
   ?\} '("{ " . " }")))
#+end_src

Shortcut for evil normal mode
#+begin_src emacs-lisp
(map! :n "g U" #'browse-url-xdg-open
      :n "g u" #'evil-upcase
      :n "g d" #'evil-downcase
      :n "g R" #'normal-mode)
#+end_src

** snippets
#+begin_src emacs-lisp :tangle no :noweb-ref editor
snippets
#+end_src

#+begin_src emacs-lisp
(setq +snippets-dir
      (expand-file-name "~/Documents/Templates/snippets"))
#+end_src

** fold
#+begin_src emacs-lisp :tangle no :noweb-ref editor
fold
#+end_src

work for =org-ellipsis= and fold in code mode
#+begin_src emacs-lisp
(setq +fold-ellipsis "⤵")
(after! org
  (setq org-startup-folded 'fold
        org-hide-drawer-startup nil))
      ;; org-hide-block-startup nil
#+end_src

** Undo
#+begin_src emacs-lisp
(with-eval-after-load 'undo-fu-session
  (defun my/undo-fu-session-drop-text-property-undo (undo-list)
    (delq nil
          (mapcar (lambda (entry)
                    ;; Text-property undo entries have the form:
                    ;;   (nil PROP VALUE BEG . END)
                    ;; Drop them so session files only persist textual edits.
                    (unless (and (consp entry) (null (car entry)))
                      entry))
                  undo-list)))

  (defun my/undo-fu-session-save-without-text-properties (fn &rest args)
    (let ((buffer-undo-list
           (my/undo-fu-session-drop-text-property-undo buffer-undo-list))
          (pending-undo-list
           (my/undo-fu-session-drop-text-property-undo pending-undo-list)))
      (apply fn args)))

  (advice-add 'undo-fu-session--save-impl :around
              #'my/undo-fu-session-save-without-text-properties))
#+end_src

** unfill
- [[https://www.emacswiki.org/emacs/UnfillParagraph][EmacsWiki: Unfill Paragraph]]
- [[https://github.com/purcell/unfill][GitHub - purcell/unfill: Functions providing the inverse of Emacs' fill-paragraph]]
#+begin_src emacs-lisp
;;; Stefan Monnier <foo at acm.org>. It is the opposite of fill-paragraph
(defun unfill-paragraph (&optional region)
  "Takes a multi-line paragraph and makes it into a single line of text."
  (interactive (progn (barf-if-buffer-read-only) '(t)))
  (let ((fill-column (point-max))
        ;; This would override `fill-column' if it's an integer.
        (emacs-lisp-docstring-fill-column t))
    (fill-paragraph nil region)))

;; Handy key definition
(define-key global-map "\M-Q" #'unfill-paragraph)
#+end_src

* Emacs
** dired
#+begin_src emacs-lisp :tangle no :noweb-ref emacs
(dired +dirvish +icons)
#+end_src

#+begin_src emacs-lisp
(after! dired
  (setq delete-by-moving-to-trash t)
  (setq dired-listing-switches
        "-l --almost-all --sort=time --human-readable --time-style=long-iso --group-directories-first --no-group")
  ;; Dirvish respects all the keybindings in `dired-mode-map'
  (map! :map dired-mode-map
        :n "e" #'dired-create-empty-file
        :n "." #'dired-omit-mode))
#+end_src

Better trash/restore file with =trash-put=, =trash-restore= from =trash-cli= package.
[[https://emacs.stackexchange.com/questions/37492/how-restore-file-from-trash][How restore file from trash?]]

~gio trash~ in =dired=
#+begin_src emacs-lisp
(defun system-move-file-to-trash (filename)
  "Trash FILENAME using the 'gio trash' command.
FILENAME should be an absolute path or resolvable from the
current 'default-directory'."
  (interactive "fTrash file: ")
  (let ((expanded-file (expand-file-name filename)))
    (unless (executable-find "gio")
      (error "'gio' command not found in your PATH."))
    (let ((exit-status (call-process "gio" nil nil nil "trash" expanded-file)))
      (unless (zerop exit-status)
        (error "Command 'gio trash %s' failed with exit status %d"
               (shell-quote-argument expanded-file) exit-status)))))
#+end_src

#+begin_src emacs-lisp
(after! dired-x
  ;; Make dired-omit-mode hide all "dotfiles"
  (setq dired-omit-files
        (concat dired-omit-files "\\|^\\..*$")))
#+end_src

** dirvish
#+begin_src toml
[dirvish]
packages=[
    "fd",
    "libvips",
    "imagemagick",
    "ffmpegthumbnailer", # may require pipewire-jack
    "mediainfo",
    "tar",
    "unzip"
]
#+end_src

#+begin_src emacs-lisp
(after! dirvish
  (setq dirvish-quick-access-entries
   '(("h" "~/"                          "Home")
     ("d" "~/Downloads/"                "Downloads")
     ("D" "~/Documents/"                "Documents")
     ("p" "~/Pictures/"                 "Pictures")
     ("l" "~/lib/"                      "Library")
     ("c" "~/.config/"                  "Config")
     ("n" "~/.Nextcloud/"               "Nextcloud")
     ("m" "/mnt/"                       "Mounts")
     ("t" "~/.local/share/Trash/files/" "TrashCan"))))
#+end_src

#+begin_src emacs-lisp
(after! dirvish
  (setq dirvish-side-width 25)
  (setq dirvish-reuse-session 'quit)
  (map!
   :map dirvish-mode-map
   :gn "S" #'dirvish-cd-into-vterm
   ;; remap previous =S= to =o=
   :gn "o" #'dirvish-quicksort))
#+end_src

#+begin_src emacs-lisp
(defun dirvish-open-binaries-externally (file fn)
  "When FN is not `dired', open binary FILE externally."
  (when-let* (((not (eq fn 'dired)))
              ((file-exists-p file))
              ((not (file-directory-p file)))
              ((member (downcase (or (file-name-extension file) ""))
                       dirvish-binary-exts)))
    ;; return t to terminate `dirvish--find-entry'.
    (prog1 t (dired-do-open))))

(add-hook 'dirvish-find-entry-hook #'dirvish-open-binaries-externally)

(after! dirvish
  ;; remove pdf
  (setq dirvish-binary-exts (remove "pdf" dirvish-binary-exts)))
#+end_src

Replace =/home/$user= to =~=
#+begin_src emacs-lisp
(defun +my/home-to-tilde (file)
  "Replace /home/$user in FILE to ~."
  (let ((home (getenv "HOME"))
        (file-name (concat file)))
    (if (s-starts-with? home file-name)
        (s-replace home "~" file-name)
      file-name)))

(defun +my/dirvish-copy-file-path (&optional multi-line)
  "Copy filepath of marked files.
If MULTI-LINE, make every path occupy a new line."
  (interactive "P")
  (let* ((files (mapcar #'file-local-name (dired-get-marked-files)))
         (related-files (mapcar #'+my/home-to-tilde files))
         (names (mapconcat #'identity related-files (if multi-line "\n" " "))))
    (dirvish--kill-and-echo (if multi-line (concat "\n" names) names))))

(after! dirvish
 (advice-add 'dirvish-copy-file-path :override #'+my/dirvish-copy-file-path))
#+end_src

Goto random line, use with [[fn:dirvish-fd]]
#+begin_src emacs-lisp
(defun goto-random-line ()
  "Go to a random line in the current buffer."
  (interactive)
  (let* ((total-lines (count-lines (point-min) (point-max)))
         (random-line (1+ (random total-lines))))
    (goto-line random-line)))
#+end_src

set =dirvish= as default directory opener.
#+begin_src fish :tangle no :eval no
xdg-mime default dirvish.desktop inode/directory
#+end_src

** tramp
[[https://github.com/alexluigit/dirvish/blob/main/docs/CUSTOMIZING.org#tramp-integration][dirvish/docs/CUSTOMIZING.org at main]]
#+begin_src emacs-lisp
(with-eval-after-load 'tramp
  ;; Enable full-featured Dirvish over TRAMP on ssh connections
  ;; https://www.gnu.org/software/tramp/#Improving-performance-of-asynchronous-remote-processes
  (connection-local-set-profile-variables
   'remote-direct-async-process
   '((tramp-direct-async-process . t)))
  (connection-local-set-profiles
   '(:application tramp :protocol "rpc")
   'remote-direct-async-process))
#+end_src

- [[https://github.com/akermu/emacs-libvterm/issues/689][akermu/emacs-libvterm#689 Tramp-login-shells custom doesn't match type]]
- [[https://github.com/akermu/emacs-libvterm/pull/706][akermu/emacs-libvterm#706 Allow using the default login shell for remote connections]]

*** tramp-rpc
[[https://github.com/ArthurHeymans/emacs-tramp-rpc][GitHub - ArthurHeymans/emacs-tramp-rpc]]

[[https://github.com/ArthurHeymans/emacs-tramp-rpc/issues/28#issuecomment-3775255423][ArthurHeymans/emacs-tramp-rpc#28]]
#+begin_src emacs-lisp :tangle packages.el
(package! tramp-rpc
  :recipe (:host github
           :repo "ArthurHeymans/emacs-tramp-rpc"
           :files ("lisp/*.el")
           :build (:not autoloads)))

(package! msgpack)
#+end_src

#+begin_src emacs-lisp
(use-package tramp-rpc
  :after tramp
  :config
  ;; Local cache directory (default: ~/.emacs.d/tramp-rpc/)
  (setq tramp-rpc-deploy-local-cache-directory "~/.cache/tramp-rpc-binaries")
  ;; Remote installation directory (default: ~/.cache/tramp-rpc)
  (setq tramp-rpc-deploy-remote-directory "~/.local/bin/tramp-rpc"))
#+end_src

File preview is not supported in this connection.
1. Please check if you have GNU ls installed over remote host.
2. Adjust your `direct-async' tramp settings, for example:

See (info "(tramp) Improving performance of asynchronous remote processes") for details.

** proxy
#+begin_src emacs-lisp
(setq url-proxy-services
   `(("no_proxy" . "^\\(localhost\\|10\\..*\\|192\\.168\\..*\\)")
     ("http"  . ,(getenv "ALL_PROXY"))
     ("https" . ,(getenv "ALL_PROXY"))))
#+end_src

* Term
** Navigation
#+begin_src emacs-lisp
(map! :leader
      (:prefix "o"
       :desc "Open terminal here" "t" #'+my/term-here
       :desc "Open terminal buffer here" "T" (cmd! (ghostel t))))
#+end_src

** vterm
*** Setup
#+begin_src toml
[vterm]
packages=[
    "libvterm",
    "cmake",
    "inetutils" # =hostname= command
]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref term
vterm
#+end_src

[[https://emacs.stackexchange.com/questions/24330/have-a-function-to-disable-close-confirmation-on-terms-work-on-all-terms-but-sh][Disable process query on exit for term-like buffers]]
#+begin_src emacs-lisp
(defun +my/disable-process-query-on-exit-h ()
  "Disable exit confirmation for the current buffer's process."
  (when-let ((proc (get-buffer-process (current-buffer))))
    (set-process-query-on-exit-flag proc nil)))

(with-eval-after-load 'vterm
  (when (+my/is-utility-daemon)
    (add-hook 'vterm-mode-hook #'+my/disable-process-query-on-exit-h)))
#+end_src

*** Navigation
#+begin_src emacs-lisp
(with-eval-after-load 'vterm
  (setq vterm-buffer-name-string "%s - vterm"
        vterm-ignore-blink-cursor nil)
  ;; TODO fixed-pitch in bpytop like
  (define-key vterm-mode-map (kbd "M-q") #'vterm-send-escape)
  (define-key vterm-mode-map (kbd "C-l") nil)
  (dolist (num (number-sequence 0 9))
      (define-key vterm-mode-map (kbd (format "M-%d" num)) nil)))
#+end_src

*** Persistence
Restore vterm buffer text and window layout across workspace restores.  The
shell process itself is not restored.

- [[https://github.com/akermu/emacs-libvterm/issues/666][akermu/emacs-libvterm#666 Integrate with desktop-save-mode]]
- [[https://bmag.github.io/2015/12/26/desktop.html][Desktop-Save Mode]]
- [[https://github.com/Bad-ptr/persp-mode.el#custom-saveload-buffer-function-example][GitHub - Bad-ptr/persp-mode.el: named perspectives(set of buffers/window conf...]]
- [[doom:modules/ui/workspaces/config.el::263][examples in doom config]]

Only plain text is saved; text properties are intentionally omitted.

A vterm buffer whose name changes (e.g. an agent terminal pushing OSC titles)
breaks =persp-mode= window restore: =window-state-put= matches windows by
buffer name, so a name that differs between save and restore drops the window
and the layout collapses on workspace switch.  Rather than advising persp's
save/restore to strip the volatile prefix, the root cause is fixed at the
source by disabling vterm's title-driven renaming on those buffers (see [[* codex ide][codex
ide]] / [[* claude code ide][claude code ide]], =vterm-buffer-name-string=).

#+begin_src emacs-lisp
(with-eval-after-load 'persp-mode
  (persp-def-buffer-save/load
   :mode 'vterm-mode :tag-symbol 'def-vterm-buffer
   :save-vars '(default-directory)
   :save-function (lambda (buf tag vars)
                    (with-current-buffer buf
                      (list tag (buffer-name buf) vars
                            (string-trim-right
                             (buffer-substring-no-properties
                              (point-min) (point-max))))))
   :load-function (lambda (savelist &rest _)
                    (cl-destructuring-bind (_ buf-name vars buf-string) savelist
                      (let ((default-directory (alist-get 'default-directory vars)))
                        (require 'vterm)
                        (with-current-buffer (get-buffer-create buf-name)
                          (erase-buffer)
                          (insert buf-string)
                          (vterm-mode)))))))
#+end_src

*** Integrations
Switch from =dirvish= into the workspace vterm and sync its working directory when
it is safe to send input at an empty prompt. This mirrors ranger's =S= shortcut.

#+begin_src emacs-lisp
(defun +my/vterm-at-empty-prompt-p ()
  "Return non-nil when the current vterm is at an empty prompt.

This relies on vterm's prompt detector.  If that private helper is not
available, refuse to send input."
  (and (fboundp 'vterm--at-prompt-p)
       (save-excursion
         (let ((evil-state (and (boundp 'evil-state) evil-state)))
           (unwind-protect
               (progn
                 (when (fboundp 'vterm-reset-cursor-point)
                   (vterm-reset-cursor-point))
                 (when (fboundp 'evil-collection-vterm-append)
                   (evil-collection-vterm-append))
                 (vterm--at-prompt-p))
             (when (and (bound-and-true-p evil-local-mode) evil-state)
               (evil-change-state evil-state)))))))

(defun dirvish-cd-into-vterm ()
  "Switch into recent vterm buffer, and cd into `default-directory` of dirvish buffer."
  (interactive)
  (let ((cur-dirvish-dir default-directory))
    (dirvish-quit)
    (if-let ((vterm-buffer (+my/workspace-first-vterm-buffer)))
        (let ((cur-vterm-dir (with-current-buffer vterm-buffer
                               default-directory)))
          (switch-to-buffer vterm-buffer)
          (when (and (not (string= cur-vterm-dir cur-dirvish-dir))
                     (+my/vterm-at-empty-prompt-p))
            (vterm-send-string
             (concat " cd " (shell-quote-argument cur-dirvish-dir)))
            (vterm-send-return)))
      (with-temp-buffer
        (setq-local default-directory cur-dirvish-dir)
        (+vterm/here t)))))
#+end_src

** ghostel
[[https://github.com/dakra/ghostel][GitHub - dakra/ghostel]] is an Emacs terminal emulator powered by =libghostty-vt=
(Ghostty's VT engine), inspired by =emacs-libvterm=.

The native dynamic module is downloaded automatically on first use: a prebuilt
binary exists for =x86_64-linux=, governed by =ghostel-module-auto-install= (default
=ask=). Trigger it manually with =M-x ghostel-download-module= if needed.

*** Setup
#+begin_src emacs-lisp :tangle packages.el
(package! ghostel)
(package! evil-ghostel)
#+end_src

#+begin_src emacs-lisp
(use-package! ghostel
  :commands ghostel
  :config
  ;; recenter
  (define-key ghostel-semi-char-mode-map (kbd "C-l") nil)
  ;; switch workspace
  (dolist (num (number-sequence 0 9))
      (define-key ghostel-semi-char-mode-map (kbd (format "M-%d" num)) nil)))

(use-package! evil-ghostel
  :after (ghostel evil)
  :hook (ghostel-mode . evil-ghostel-mode))
#+end_src

*** Navigation
#+begin_src emacs-lisp
(defun +my/ghostel-close-window-on-kill-h ()
  "Close the window displaying the current Ghostel buffer."
  (let ((windows (get-buffer-window-list (current-buffer) nil t)))
    (run-at-time
     0 nil
     (lambda (windows)
       (dolist (window windows)
         (when (window-live-p window)
           (ignore-errors (delete-window window)))))
     windows)))

(defun +my/term-here ()
  "Open a new Ghostel terminal below the current window."
  (interactive)
  (let ((buffer (let ((display-buffer-overriding-action
                       '((display-buffer-below-selected)
                         (window-height . 12))))
                  (ghostel t))))
    (with-current-buffer buffer
      (setq-local ghostel-kill-buffer-on-exit t)
      (add-hook 'kill-buffer-hook #'+my/ghostel-close-window-on-kill-h nil t))))

(defun +my/kill-frame-ghostel-buffer-h (frame)
  "Kill the Ghostel buffer associated with FRAME."
  (when-let ((buffer (frame-parameter frame '+my/ghostel-buffer)))
    (when (buffer-live-p buffer)
      (kill-buffer buffer))))

(add-hook 'delete-frame-functions #'+my/kill-frame-ghostel-buffer-h)
#+end_src

* Checkers
** Spell checker
#+begin_src toml
[spell]
packages=["aspell", "aspell-en"]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref checkers
(spell +aspell
       +everywhere)
#+end_src

#+begin_src emacs-lisp
(after! ispell
  (setq ispell-personal-dictionary
        (expand-file-name ".pws" "~/.Nextcloud/ispell/")))
#+end_src

#+begin_src emacs-lisp
(dolist (face '(org-level-1 org-level-2 org-level-3
                font-lock-function-name-face help-key-binding))
  (cl-pushnew face (alist-get 'org-mode +spell-excluded-faces-alist)))

(dolist (face '(font-lock-constant-face tex-math font-lock-comment-face))
  (cl-pushnew face (alist-get 'latex-mode +spell-excluded-faces-alist)))
#+end_src

Only hint spell error for English words!
#+begin_src emacs-lisp
(defconst +my/spell-fu-english-word-regexp
  "\\b\\([A-Za-z]+\\(['’][A-Za-z]+\\)?\\)\\b")

(add-hook 'spell-fu-mode-hook
          (lambda ()
            (setq-local spell-fu-word-regexp
                        +my/spell-fu-english-word-regexp)))
#+end_src

* Tools
** lookup
#+begin_src toml
[lookup]
packages=["sqlite", "wordnet-common"]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref tools
(lookup
 +docsets
 +dictionary)
#+end_src

#+begin_src emacs-lisp
(add-to-list '+lookup-provider-url-alist '("Brave" "https://search.brave.com/search?q=%s"))
(add-to-list '+lookup-provider-url-alist '("Inspire" "https://inspirehep.net/literature?q=%s"))
#+end_src

** llm
#+begin_src emacs-lisp :tangle no :noweb-ref tools
llm
#+end_src

#+begin_src emacs-lisp
(with-eval-after-load 'gptel
  (setq gptel-include-reasoning 'ignore
        gptel-expert-commands t
        gptel-track-media t
        gptel-log-level 'info)
  ;; avoid headings as prompt
  (setf (alist-get 'org-mode gptel-prompt-prefix-alist) "** "
        (alist-get 'org-mode gptel-response-prefix-alist) "*Response:*\n")
  (add-hook! 'gptel-pre-response-hook
    (outline-previous-heading)
    (recenter-top-bottom 1))
  ;; (add-hook 'gptel-post-stream-hook 'gptel-auto-scroll)
  ;; (add-hook 'gptel-post-response-functions 'gptel-end-of-response))
  (load-in-doom-dir "private/gpt.el"))
#+end_src

*** gptel tweaks
After [[cmd:gptel-org-set-topic]], remove the top heading for collect conversation.
#+begin_src emacs-lisp
(defun +my/gptel-org-rm-upper-heading ()
  "Remove upper level heading line."
  (while (re-search-backward "\\(?:^\\* .+$\\)[[:space:]]+" nil t)
    (delete-region (match-beginning 0) (match-end 0))))

(add-hook 'gptel-prompt-filter-hook #'+my/gptel-org-rm-upper-heading)
#+end_src

#+begin_src elisp
(defun gptel-shift-response-heading-level (start end)
  "Shift all Org headings in region so smallest is level 3 (***).
If the last line at END starts with '** ', exclude it from shifting."
  (interactive "r")
  (save-excursion
    ;; Adjust end if needed
    (goto-char end)
    (when (and (beginning-of-line) (looking-at "^\\*\\* "))
      (setq end (max start (line-end-position -1))))
    ;; Find min level and shift
    (let ((min-level (save-excursion
                       (goto-char start)
                       (cl-loop while (re-search-forward "^\\(\\*+\\) " end t)
                                minimize (length (match-string 1))))))
      (when (and min-level (< min-level 3))
        (let ((shift (- 3 min-level)))
          (goto-char start)
          (while (re-search-forward "^\\(\\*+\\) " end t)
            (replace-match (concat (make-string (+ (length (match-string 1)) shift) ?*) " ") t t)))))))

(add-hook 'gptel-post-response-functions #'gptel-shift-response-heading-level)
#+end_src

*** Tools Collection
[[https://github.com/karthink/gptel/wiki/Tools-collection][Tools collection · karthink/gptel Wik...]]
#+begin_src emacs-lisp :tangle packages.el
(package! gptel-got
  :recipe (:host nil
	   :repo "https://codeberg.org/bajsicki/gptel-got"))
#+end_src

#+begin_src emacs-lisp
(use-package gptel-got :after gptel)
#+end_src

=codel= have merged into this =llm-tool-collection= fork. see [[https://github.com/ultronozm/codel.el/issues/2][ultronozm/codel.el#2 Errors with gpte...]]
#+begin_src emacs-lisp :tangle packages.el
(package! llm-tool-collection
  :recipe (:type git :host github :repo "ultronozm/llm-tool-collection"))
#+end_src

#+begin_src emacs-lisp
(use-package llm-tool-collection
  :after gptel
  :config
  (mapcar (apply-partially #'apply #'gptel-make-tool)
        (llm-tool-collection-get-all)))
#+end_src

And more in [[https://github.com/munen/emacs.d?tab=readme-ov-file#tool-use][GitHub - munen/emacs.d: My emacs conf...]]

#+begin_src emacs-lisp :tangle packages.el
(package! gptel-agent)
#+end_src

#+begin_src emacs-lisp
(use-package gptel-agent :defer t)
#+end_src

*** Others
#+begin_src emacs-lisp
(after! gptel-quick
  (setq gptel-quick-model 'qwen3:14b)
  (setq gptel-quick-backend (cdr (assoc-string "ollama" gptel--known-backends))))
#+end_src

** agent
*** agent-shell
#+begin_src toml
[agent]
packages=[
    "claude-agent-acp",
    "codex-acp"
]
#+end_src

#+begin_src emacs-lisp :tangle packages.el
(package! shell-maker)
(package! acp)
(package! agent-shell)
(package! agent-shell-notifications
  :recipe (:host github :repo "zackattackz/agent-shell-notifications"))
(package! agent-shell-org-transcript
  :recipe (:host github :repo "lllShamanlll/agent-shell-org-transcript"))
#+end_src

#+begin_src emacs-lisp
(use-package! agent-shell
  :commands (agent-shell)
  :config
  (setq agent-shell-context-sources '(files region error))
  ;; Evil state-specific RET behavior: insert mode = newline, normal mode = send
  (evil-define-key 'insert agent-shell-mode-map (kbd "RET") #'newline)
  (evil-define-key 'normal agent-shell-mode-map (kbd "RET") #'comint-send-input)

  ;; Configure *agent-shell-diff* buffers to start in Emacs state
  (add-hook 'diff-mode-hook
	    (lambda ()
	      (when (string-match-p "\\*agent-shell-diff\\*" (buffer-name))
		(evil-emacs-state))))
  (add-to-list 'agent-shell-mcp-servers
               '((name . "emcp")
                 (type . "http")
                 (headers . ())
                 (url . (lambda ()
                          (require 'emcp)
                          (let ((server (emcp-start emcp-default-profile)))
                            (emcp-server-url server))))))
  )
#+end_src

#+begin_src emacs-lisp
(use-package agent-shell-notifications
  :after agent-shell
  :hook (agent-shell-mode . agent-shell-notifications-mode))
#+end_src

#+begin_src emacs-lisp
(use-package agent-shell-org-transcript
  :after agent-shell
  :config
  (setq agent-shell-org-transcript-directory "~/Documents/org/agent-shell/"))
#+end_src

*** claude code ide
=web-server= is needed by the MCP HTTP server; declare it explicitly so straight
pulls it on a fresh sync.
#+begin_src emacs-lisp :tangle packages.el
(package! web-server)

(package! claude-code-ide
  :recipe (:host github :repo "manzaltu/claude-code-ide.el"))
#+end_src

#+begin_src emacs-lisp
(use-package! claude-code-ide
  :bind ("C-c c" . claude-code-ide-menu) ; Set your favorite keybinding
  :init
  ;; Use ghostel (libghostty-vt) as the terminal backend instead of the
  ;; default vterm.  Valid values: 'vterm, 'eat, 'ghostel.
  (setq claude-code-ide-terminal-backend 'ghostel)
  :config
  (claude-code-ide-emacs-tools-setup)) ; Optionally enable Emacs MCP tools
#+end_src

The vterm backend renames its buffer from shell OSC titles via
=vterm-buffer-name-string=.  Agent CLIs push a volatile activity title (e.g. a
spinner prefix), so the buffer name flips between save and restore and
=persp-mode= drops the window on workspace switch (see [[* Persistence][Persistence]]).  Pin a
stable name on agent terminals by disabling title-driven renaming there.  This
is buffer-local and leaves ordinary vterm buffers untouched.
#+begin_src emacs-lisp
(defun +my/vterm-disable-title-rename-for-agents-h ()
  "Disable OSC-title buffer renaming in claude/codex vterm buffers.
Keeps the buffer name stable so `persp-mode' restores its window."
  (when (string-match-p "\\*\\(claude-code\\|codex\\)" (buffer-name))
    (setq-local vterm-buffer-name-string nil)))

(add-hook 'vterm-mode-hook #'+my/vterm-disable-title-rename-for-agents-h)
#+end_src

** MCP server
#+begin_src emacs-lisp :tangle packages.el
(package! emcp)
#+end_src

#+begin_src emacs-lisp
(use-package! emcp
  :after agent-shell
  :config
  (add-hook 'emcp-confirm-mode-hook #'evil-emacs-state))
#+end_src

** magit
#+begin_src emacs-lisp :tangle no :noweb-ref tools
magit
#+end_src

- [[https://github.com/TheLocehiliosan/yadm][GitHub - TheLocehiliosan/yadm: Yet Another Dotfiles Manager]]
- [[https://www.reddit.com/r/emacs/comments/gjukb3/yadm_magit/][reddit:yadm+magit]]

#+begin_src emacs-lisp
(defun yadm-status ()
  (interactive)
  (magit-status "/yadm::"))
(map! :leader
      (:prefix "g"
       :desc "yadm-status" "a" #'yadm-status))
;; see `man yadm'
(with-eval-after-load 'tramp
  (add-to-list 'tramp-methods
               '("yadm"
                 (tramp-remote-shell "/bin/bash")
                 (tramp-remote-shell-args ("-c"))
                 (tramp-login-program "yadm")
                 (tramp-login-args (("enter"))))))
#+end_src

Restore focus to origin window after viewing a commit and pressing =q=.
#+begin_src emacs-lisp
(defvar +my/magit-origin-window nil)
(with-eval-after-load 'magit
  (advice-add 'magit-show-commit :before
    (lambda (&rest _)
      (setq +my/magit-origin-window (selected-window))))
  (advice-add 'magit-mode-quit-window :after
    (lambda (&rest _)
      (when (and +my/magit-origin-window
                 (window-live-p +my/magit-origin-window))
        (select-window +my/magit-origin-window)
        (setq +my/magit-origin-window nil)))))
#+end_src

If you use =fish= shell, you may change ~fish_prompt~. see [[file:~/.config/fish/config.fish]]

[[cmd:magit-stage]] (visually stage hunks) may not work in =yadm=, which cause emacs
to hang, use [[kbd:E s]] ([[cmd:magit-ediff-stage]]) instead.
[[https://github.com/magit/magit/issues/719][magit/magit#719 Magit process hangs when trying to stage a hunk]]

** transient
- [[file:~/.config/emacs/modules/tools/magit/config.el::transient-display-buffer-action]]
- [[https://github.com/magit/transient/issues/338#issuecomment-2528948033][magit/transient#338 Transient window doesn't come back if display-action is set]]
- [[https://github.com/karthink/gptel/issues/583][karthink/gptel#583 Transient issue when selecting a model in `gptel-menu`]]
#+begin_src emacs-lisp :tangle no
(after! (transient magit gptel)
  (setq transient-display-buffer-action
        '(display-buffer-below-selected
          (dedicated . t)
          (inhibit-same-window . t)))
  (setq transient-show-during-minibuffer-read t))
#+end_src

see also [[https://github.com/karthink/gptel/issues/583][karthink/gptel#583 Transient issue when selecting a model in `gptel-menu`]]

*** transient-posframe
[[https://github.com/yanghaoxie/transient-posframe/blob/master/transient-posframe.el][transient-posframe/transient-posframe]]
#+begin_src emacs-lisp
(with-eval-after-load 'transient
  (defun my/transient-posframe-display-buffer (buffer alist)
    "Display transient BUFFER in a child frame."
    (when (and (fboundp 'posframe-show)
               (fboundp 'posframe-workable-p)
               (posframe-workable-p))
      (let ((pf (posframe-show
                 buffer
                 :poshandler #'posframe-poshandler-frame-bottom-center
                 :accept-focus nil
                 :font "ComicShannsMono Nerd Font 8"
                 :min-width 40
                 :border-width 2
                 :border-color "gray50")))
        (redisplay t)
        (and (frame-live-p pf) (frame-root-window pf)))))

  ;; `transient--fit-window-to-buffer' calls `fit-frame-to-buffer' when the
  ;; window has no parent (i.e. posframe root window).  The posframe child frame
  ;; shares the parent frame's minibuffer window; `fit-frame-to-buffer' includes
  ;; that shared window in its layout calculation and resizes it, causing the
  ;; parent frame's minibuffer to grow unexpectedly.  Skip `fit-frame-to-buffer'
  ;; for child frames and fit the window directly instead.
  (defadvice! +my/transient--fit-window-skip-child-frame-a (orig-fn window)
    :around #'transient--fit-window-to-buffer
    (if (frame-parameter (window-frame window) 'parent-frame)
        (let ((fit-window-to-buffer-horizontally t)
              (window-resize-pixelwise t)
              (window-size-fixed nil))
          (set-window-parameter window 'window-preserved-size nil)
          (fit-window-to-buffer window nil 1)
          (set-window-parameter window 'window-preserved-size
                                (list (window-buffer window)
                                      (window-body-width window t)
                                      (window-body-height window t))))
      (funcall orig-fn window))))
#+end_src

- [ ] still buggy, only work after manually execute this block.
- Notes:
  - daemon mode still has a first-popup issue: the first transient posframe in a
    new client frame may fail to appear, while later ones usually work
  - this block intentionally keeps the current workaround behavior because it is
    stable enough after that first failure

#+begin_src emacs-lisp
(after! (:or magit dirvish gptel)
  (setq transient-display-buffer-action
        '(my/transient-posframe-display-buffer
          (dedicated . t)
          (inhibit-same-window . t))))
#+end_src

- [ ] try to fixed transient menu in =dirvish=
#+begin_src emacs-lisp
(defun transient-posframe--delete ()
  "Delete transient posframe."
  (posframe-delete-frame transient--buffer-name)
  (posframe--kill-buffer transient--buffer-name))

(advice-add 'transient--delete-window :override #'transient-posframe--delete)
#+end_src

** pdf
#+begin_src emacs-lisp :tangle no :noweb-ref tools
pdf
#+end_src

default pdf viewer in emacs
- [[http://alberto.am/2020-04-11-pdf-tools-as-default-pdf-viewer.html][pdf-tools as the default PDF viewer in Emacs]]

#+begin_src emacs-lisp
(after! pdf-tools
  (setq-default pdf-view-display-size 'fit-width))

(after! latex (setq +latex-viewers '(pdf-tools evince okular)))

;; to have the buffer refresh after compilation
(add-hook 'TeX-after-compilation-finished-functions
          #'TeX-revert-document-buffer)

;; always use midnight view mode
(add-hook! 'pdf-view-mode-hook #'pdf-view-midnight-minor-mode)
#+end_src

Selection in =pdf-tools= when evil mode enabled
- [[https://github.com/doomemacs/doomemacs/issues/6286#issuecomment-1870216583][doomemacs/doomemacs#6286 `evil` interfering with PDF text selection/highlight...]]

Correct the file name path if it is a WSL path in Windows or an absolute path
inadvertently synced with a network disk. For =pdf-sync-view=, the source file
was correctly identified only after making this adjustment.
#+begin_src emacs-lisp
(defun +my/synced-true-path (filename)
  "Rewrite the FILENAME assuming it from synced netdisk (or WSL).

When from netdisk, ensure they have same directory structure with
respect to your home."
  (if (s-starts-with-p "//wsl.localhost" filename)
      (setq filename (replace-regexp-in-string "^//wsl.localhost/\\w+" "" filename)))
  (unless (s-starts-with-p (getenv "HOME") filename)
    (setq filename (replace-regexp-in-string "^/home/\\w+" (getenv "HOME") filename)))
  filename)

(defun +my/pdf-sync-backward-search (x y &optional page)
  "Go to the source corresponding to image coordinates X, Y.

Try to find the exact position, if
`pdf-sync-backward-use-heuristic' is non-nil."
  (cl-destructuring-bind (source finder)
      (pdf-sync-backward-correlate x y page)
    (setq source (+my/synced-true-path source))
    (pop-to-buffer (or (find-buffer-visiting source)
                       (find-file-noselect source))
                   pdf-sync-backward-display-action)
    (push-mark)
    (funcall finder)
    (run-hooks 'pdf-sync-backward-hook)))

(advice-add 'pdf-sync-backward-search :override #'+my/pdf-sync-backward-search)
#+end_src

Auto view =.ps= file
#+begin_src emacs-lisp
(add-hook 'ps-mode-hook 'doc-view-toggle-display)
#+end_src

** go-translate
#+begin_src emacs-lisp :tangle packages.el
(package! gt)
#+end_src

#+begin_src emacs-lisp
(use-package gt
  :bind ("C-c t" . gt-translate)
  :config
  (setq gt-langs '(en zh))
  (setq gt-default-translator
        (gt-translator
         :engines (list (gt-youdao-dict-engine) (gt-youdao-suggest-engine))
         ;; :engines (gt-google-engine)
         :render (gt-buffer-render)))
  (set-popup-rule!
    "^\\*gt-result\\*"
    :side 'left :size 60 :slot -2 :select t))
#+end_src

** pacdiff
#+begin_src emacs-lisp :tangle packages.el
(package! pacdiff)
#+end_src

#+begin_src emacs-lisp
(use-package! pacdiff)
#+end_src

** tldr
#+begin_src emacs-lisp :tangle packages.el
(package! tldr)
#+end_src

* Lang
** Latex
*** Setup
#+begin_src toml
[latex]
enabled="not is_wsl"
packages=[
    "miktex", "texlab",
    # for `latexindent.pl` to work, which is called by `+format/buffer`
    "perl-yaml-tiny", "perl-file-homedir"
]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref lang
(latex +lsp +fold +cdlatex)
#+end_src

Invoke =latex.exe= on windows.
#+begin_src emacs-lisp
(if (featurep :system 'wsl)
    (setq LaTeX-command "latex.exe"
          TeX-command "latex.exe"))
#+end_src

#+begin_src emacs-lisp
(after! evil-tex
  (setq evil-tex-include-newlines-in-envs nil
        evil-tex-select-newlines-with-envs nil))
#+end_src

#+begin_src emacs-lisp
(with-eval-after-load 'latex
  (setq LaTeX-clean-intermediate-suffixes
        (delete "\\.synctex\\.gz" (copy-sequence LaTeX-clean-intermediate-suffixes)))
  (dolist (suffix '("\\.loc" "\\.soc" "Notes\\.bib"))
    (add-to-list 'LaTeX-clean-intermediate-suffixes suffix))
  (dolist (suffix '("\\.bbl" "\\.synctex\\.gz"))
    (add-to-list 'LaTeX-clean-output-suffixes suffix)))
#+end_src

*** Format
[[fn:latex-indent]] [[cmd:LaTeX-fill-buffer]]
- [[https://github.com/lassik/emacs-format-all-the-code/issues/127][lassik/emacs-format-all-the-code#127 LaTeX formatting]]

[[cmd:+format/buffer]] default installed by =miktex=
- [[https://github.com/cmhughes/latexindent.pl][GitHub - cmhughes/latexindent.pl: Perl script to add indentation (leading hor...]]
#+begin_src emacs-lisp
(after! apheleia
  (set-formatter! 'latexindent '("latexindent" "-l" "-r" "--logfile=/dev/null")
    :modes '(LaTeX-mode)))
#+end_src

*** Editing
add =XeTeX= mode in =TeX/LaTeX=
- [[https://tex.stackexchange.com/a/21205][emacs - AUCTeX and XeTeX - TeX - LaTeX Stack Exchange]]
- [[https://stackoverflow.com/a/65179402][emacs - Add XeLaTeX to the command li...]]

Most convenient way, still use =LATEX= as compile command.
#+begin_src tex :tangle no
% -*- TeX-engine: xetex; -*-
#+end_src

=cdlatex=
#+begin_src emacs-lisp
(map! :map cdlatex-mode-map
  :i "TAB" #'cdlatex-tab)
#+end_src

[[https://tex.stackexchange.com/questions/254539/latextidy-in-emacs][formatting - LaTeXTidy in Emacs - TeX - LaTeX Stack Exchange]]

#+begin_src emacs-lisp
(after! cdlatex
  (setq cdlatex-insert-auto-labels-in-env-templates nil))
#+end_src

#+begin_src emacs-lisp
(with-eval-after-load 'cdlatex
  ;; add/override math modifier after "=":
  ;;  =b  -> \mathbm{...}
  ;;  =B  -> \mathbbm{...}
  ;;
  ;; Note: you still need the corresponding LaTeX packages:
  ;;   \usepackage{bm}   for \mathbm (usually via \bm / \boldsymbol)
  ;;   \usepackage{bbm}  for \mathbbm
  (dolist (it '((?b "\\mathbm" nil t nil nil)
                (?B "\\mathbbm" nil t nil nil)))
    (setf (alist-get (car it) cdlatex-math-modify-alist)
          (cdr it))))
#+end_src

** lua
#+begin_src toml
[lua]
enabled="not is_wsl"
packages=["lua-language-server"]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref lang
(lua +lsp)
#+end_src

lsp support
#+begin_src emacs-lisp
(after! lua-mode
  (setq lsp-clients-lua-language-server-bin "/usr/bin/lua-language-server")
  (setq lsp-clients-lua-language-server-main-location "/usr/lib/lua-language-server/bin/main.lua")
  (setq lsp-clients-lua-language-server-args '("-E" "--logpath" "/tmp/lua-language-server"))
  ;; (lsp-clients-lua-language-server-command '("lua-language-server" "-E"))
  (setq lsp-clients-lua-language-server-command nil))
#+end_src

ligatures
#+begin_src emacs-lisp
(after! lua-mode
  (set-ligatures! 'lua-mode
    :def "function"
    :return "return"
    :and "and"
    :or "or"
    :not "not"
    :true "true"
    :false "false"
    :for "for"))
#+end_src

** org
*** Setup
#+begin_src toml
[org]
packages=[
    "xclip",
    "maim",
    "graphviz"
]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref lang
(org
 +hugo
 +dragndrop
 +jupyter
 +noter
 +present
 +pandoc
 +pretty
 +roam)
#+end_src

*** Core
**** org modern
Fix function link recognized as footnote.
#+begin_src emacs-lisp
(use-package org-modern
  :init
  (setq org-modern-footnote nil)
  :config
  (setq org-modern-star 'replace))
#+end_src

Not the configuration of =org-modern= package, but they should be in same
category.

#+begin_src emacs-lisp
(defun +my/org-stronger-emphasis ()
  "Make *bold* and /italic/ stand out more in org buffers."
  (face-remap-add-relative 'bold
                           '(:foreground "orange red" :weight extra-bold))
  (face-remap-add-relative 'italic
                           '(:foreground "deep sky blue" :slant italic)))

(add-hook 'org-mode-hook #'+my/org-stronger-emphasis)
#+end_src

**** org appear
Very useful package for "automatic visibility toggling depending on cursor
position"! Move on following latex to test.
#+begin_quote
\alpha_{1} + \beta^{2}
#+end_quote

#+begin_src emacs-lisp
(after! org-appear
  (setq org-appear-autolinks t
        org-appear-autosubmarkers t
        org-appear-inside-latex t))
#+end_src

**** agenda
#+begin_src emacs-lisp
(setq org-directory "~/Documents/org/"
      org-agenda-files '("agenda/todos.org" "agenda/projects.org")
      org-agenda-start-with-log-mode t
      org-agenda-prefix-format '((agenda . " %i %-12:c%?-12t% s")
                                 (todo   . " ")
                                 (tags   . " %i %-12:c")
                                 (search . " %i %-12:c"))
      org-log-done 'time
      org-log-into-drawer t
      org-startup-numerated t
      org-image-actual-width 400
      org-duration-format '((special . h:mm))
      org-startup-with-inline-images t
      org-refile-targets '(("archive.org" :maxlevel . 1)
                           ("projects.org")))
#+end_src

#+begin_src emacs-lisp
(map! :leader
      :desc "Org agenda" "=" #'org-agenda)
#+end_src

[[https://emacs.stackexchange.com/a/7840][saving - How do I automatically save org-mode buffers? - Emacs Stack Exchange]]
#+begin_src emacs-lisp
(after! org
  ;;(org-clock-persist 'history)
  (org-clock-persistence-insinuate)
  (advice-add 'org-refile :after 'org-save-all-org-buffers)
  (advice-add 'org-agenda-quit :before 'org-save-all-org-buffers))
#+end_src

custom agenda view from
- [[https://www.labri.fr/perso/nrougier/GTD/index.html#org9f2e38c][Get Things Done with Emacs]]
#+begin_src emacs-lisp
(setq org-agenda-custom-commands
      '(("g" "Get Things Done (GTD)"
         ((agenda ""
                  ((org-agenda-skip-function
                    '(org-agenda-skip-entry-if 'deadline))
                   (org-deadline-warning-days 0)
                   (org-agenda-start-day "-1d")
                   (org-agenda-span 4)))
          (todo "STRT"
                ((org-agenda-skip-function
                  '(org-agenda-skip-entry-if 'deadline))
                 (org-agenda-prefix-format "  %i %-12:c [%e] ")
                 (org-agenda-overriding-header "\nTasks\n")))
          (tags-todo "inbox"
                     ((org-agenda-prefix-format "  %?-12t% s")
                      (org-agenda-overriding-header "\nInbox\n")))
          (tags "CLOSED>=\"<today>\""
                ((org-agenda-overriding-header "\nCompleted today\n")))))))
#+end_src

#+begin_src emacs-lisp
(after! org-capture
  (setq org-capture-templates
        `(("i" "Inbox" entry (file "agenda/todos.org")
           "* TODO %?\n%U\n%i" :empty-lines 1 :prepend t)
          ("@" "Inbox [mu4e]" entry (file "agenda/todos.org")
           "* TODO Reply to \"%a\"\n%U\n%i" :empty-lines 1 :prepend t)
          ("n" "Inbox [note]" entry (file "agenda/todos.org")
           "* TODO [%a] %? %^G\n%U\n%i" :empty-lines 1 :prepend t))))
#+end_src

- [[https://stackoverflow.com/a/50875921][emacs - org-mode capture : dynamic file name - Stack Overflow]]
- [[https://github.com/daviwil/emacs-from-scratch/blob/c55d0f5e309f7ed8ffa3c00bc35c75937a5184e4/init.el][emacs-from-scratch/init.el at c55d0f5e309f7ed8ffa3c00bc35c75937a5184e4 · davi...]]

*** Babel
**** org-babel
Skip executing org source blocks within commented headings. To optimize,
consider advising [[fn:org-babel-map-executables]]
#+begin_src emacs-lisp
(defun +my/org-babel-execute-buffer (&optional arg)
  "Execute source code blocks in a buffer.
Call `org-babel-execute-src-block' on every source block in
the current buffer."
  (interactive "P")
  (org-babel-eval-wipe-error-buffer)
  (org-save-outline-visibility t
    (org-babel-map-executables nil
      (unless (org-in-commented-heading-p)
        (if (memq (org-element-type (org-element-context))
                  '(babel-call inline-babel-call))
            (org-babel-lob-execute-maybe)
          (org-babel-execute-src-block arg))))))

(advice-add 'org-babel-execute-buffer :override #'+my/org-babel-execute-buffer)
#+end_src

Restore window-start after execute subtree. For hook based implement for all
[[fn:narrow-to-region]] see:
- [[https://emacs.stackexchange.com/questions/13556/restoring-position-in-window-after-narrowing][Restoring position in window after narrowing - Emacs Stack Exchange]]

#+begin_src emacs-lisp
(defun +my/org-babel-execute-subtree (&optional arg)
  "Execute source code blocks in a subtree.
Call `org-babel-execute-src-block' on every source block in
the current subtree, passing over the prefix argument ARG."
  (interactive "P")
  (let ((original-start (window-start)))
    (save-restriction
      (save-excursion
        (org-narrow-to-subtree)
        (org-babel-execute-buffer arg)))
    (set-window-start (selected-window) original-start)))

(advice-add 'org-babel-execute-subtree :override #'+my/org-babel-execute-subtree)
#+end_src

*** Jupyter
**** jupyter
#+begin_src toml
[jupyter]
packages=["jupyter-notebook"]
#+end_src

start session only when exactly execute it.
#+begin_src emacs-lisp
(after! jupyter
  (setq jupyter-org-auto-connect nil))
#+end_src

[[https://github.com/doomemacs/doomemacs/issues/7354][doomemacs/doomemacs#7354 Jupyter fails to function after upgrade]]
#+begin_src emacs-lisp
(with-eval-after-load 'ob-jupyter
 (org-babel-jupyter-aliases-from-kernelspecs))
#+end_src

#+begin_src emacs-lisp
(after! ob-jupyter
  ;; (push :text/html jupyter-org-mime-types)
  (set-popup-rule!
    "^\\*jupyter-traceback"
    :side 'bottom :size 10 :slot -2 :select t))
#+end_src

[[https://github.com/emacs-jupyter/jupyter/issues/607][emacs-jupyter/jupyter#607 'wrong-type...]]
#+begin_src emacs-lisp
(defun my/jupyter-org-results-drawer-pre-blank-fix (element)
  "Advice to ensure the RESULTS drawer has a :pre-blank 0 property.
This prevents 'wrong-type-argument wholenump nil' errors in newer Org versions."
  (if (and element (eq (org-element-type element) 'drawer))
      (progn
        (org-element-put-property element :pre-blank 0)
        (org-element-put-property element :post-blank 1)
        element)
    element))

(advice-add 'jupyter-org-results-drawer
            :filter-return
            #'my/jupyter-org-results-drawer-pre-blank-fix)
#+end_src

To view contents of =.ipynb= file, see
- [[https://github.com/astoff/code-cells.el][GitHub - astoff/code-cells.el: Emacs utilities for code split into cells, inc...]]

Possible issues
- [[https://github.com/emacs-jupyter/jupyter/issues/584][emacs-jupyter/jupyter#584 `jupyter-or...]]
- [[https://github.com/doomemacs/doomemacs/issues/3171][doomemacs/doomemacs#3171 if: Need a v...]]
- [[https://github.com/emacs-jupyter/jupyter/issues/575][emacs-jupyter/jupyter#575 Remote kern...]]
- [ ] [[https://github.com/emacs-jupyter/jupyter/issues/558][emacs-jupyter/jupyter#558 Jupyter and...]]
- [ ] =(wrong-type-argument stringp nil)=

**** jupyter-ext
#+begin_src emacs-lisp :tangle packages.el
(package! jupyter-ext
  :recipe (:host github
           :repo "fakeGenuis/jupyter-ext"))
#+end_src

#+begin_src emacs-lisp
(use-package! jupyter-ext
  :commands jupyter-org-transient
  :init
  (map! :map org-mode-map
        :n ";" #'jupyter-org-transient)
  :config
  ;; A tweaked completion at point function for corfu
  (advice-add 'jupyter-completion-at-point :override #'jupyter-ext-completion-at-point))
#+end_src

#+begin_src emacs-lisp
(after! ob-core
  ;; with multiple output and =:async yes=, text mass up after `example` block
  (setq org-babel-min-lines-for-block-output 256))
#+end_src

Intent mainly with [[file:::wolfram in jupyter]], respect to doom's org babel lazy load
#+begin_src emacs-lisp
(defvar +my/jupyter-langs '()
  "A list of language that use jupyter override.")

(add-hook '+org-babel-load-functions
  (defun +org-babel-load-jupyter-override-h (lang)
    ;; don't multi run `org-babel-jupyter-override-src-block'
    (unless (boundp 'org-babel-header-args:jupyter)
      (require 'ob-jupyter))
        ;; or even org-babel-header-args:%s will be reset
    (when-let ((lang-name (symbol-name lang))
               (_ (member lang-name +my/jupyter-langs)))
      (set (intern (format "org-babel-default-header-args:jupyter-%s" lang-name))
           (symbol-value (intern (format "org-babel-default-header-args:%s" lang-name))))
      (org-babel-jupyter-override-src-block lang-name)))
  -90)
#+end_src

**** ob-async
Session async have been include in org mode, see how to implement async using
built in method.
- [[https://github.com/jackkamm/ob-session-async][GitHub - jackkamm/ob-session-async: Asynchronous org-mode session evaluation]]
- [[https://github.com/emacs-mirror/emacs/blob/a7cb220523d881449a2dba683e7358b3312fd482/etc/ORG-NEWS#L863][emacs/etc/ORG-NEWS at a7cb220523d881449a2dba683e7358b3312fd482 · emacs-mirror...]]

This branch mainly fix =apply: Wrong number of arguments= of advice
[[cmd:ob-async-org-babel-execute-src-block]]
- [[https://github.com/astahlman/ob-async/pull/96][astahlman/ob-async#96 Update signature and skip :session blocks by stsquad]]

#+begin_src emacs-lisp :tangle no
(package! ob-async
  :pin nil
  :recipe (:host github
           :repo "stsquad/ob-async"
           :branch "update-signature-skip-session"))
#+end_src

*** Knowledge
**** org-noter
#+begin_src emacs-lisp
(after! org-noter
  (org-noter-set-doc-split-fraction '(0.75 . 0.25)))
#+end_src

**** org-roam
#+begin_src emacs-lisp
(setq org-roam-directory (expand-file-name "roam/" org-directory))
(after! org-roam
  (setq org-roam-dailies-capture-templates
   '(("d" "default" entry "* %?\n[%<%Y-%m-%d %H:%M>]\n"
      :if-new (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n")))))
#+end_src

#+begin_src emacs-lisp
(after! org-roam
  (setq org-roam-graph-viewer "librewolf")
  (setq org-roam-graph-link-hidden-types
        '("file" "http" "https" "attachment" "zotero"
          "fuzzy" "doom-module" "kbd" "fn")))
#+end_src

**** zotxt
#+begin_src emacs-lisp :tangle packages.el
(package! zotxt)
#+end_src

#+begin_src emacs-lisp
(defun org-zotxt-get-attachment-path ()
  "Get attachment file path"
  (interactive "P")
  (let ((item-id (org-zotxt-extract-link-id-at-point)))
    (deferred:$
      (zotxt--request-deferred
       (format "%s/items" zotxt-url-base)
       :params `(("key" . ,item-id) ("format" . "paths"))
       :parser 'json-read)
      (deferred:nextc it
        (lambda (response)
          (let ((paths (cdr (assq 'paths (elt (request-response-data response) 0)))))
            (org-zotxt-choose-path paths))))
      (deferred:error it #'zotxt--deferred-handle-error)
      (if zotxt--debug-sync (deferred:sync! it)
        (deferred:nextc it
          (lambda (path) path))))))

(defun +my/tilde-home-path (path)
  "covert path starts with /home/$usr/ to '~'"
  (interactive)
  (let ((home (getenv "HOME")))
    (if (string-prefix-p home path)
        (string-join `("~" ,(string-remove-prefix home path)) "")
      path)))

(defun org-zotxt-copy-attachment-path ()
  "Open attachment of Zotero items linked at point.
Opens with `org-open-file', see for more information about ARG."
  (interactive)
  (deferred:$
    (deferred:next
      (lambda ()
        (org-zotxt-get-attachment-path)))
    (deferred:nextc it
      (lambda (path)
        (let ((new-path (+my/tilde-home-path path)))
          (kill-new new-path)
          (message "\"%s\" send to system clipboard!" new-path))))))
#+end_src

[[http://www.mkbehr.com/posts/a-research-workflow-with-zotero-and-org-mode/][A research workflow with Zotero and Org mode | mkbehr.com]]
#+begin_src emacs-lisp
(use-package zotxt
  :hook (org-mode . org-zotxt-mode)
  :config
  (setq zotxt-default-bibliography-style "mkbehr-short"))

(map! :map org-zotxt-mode-map
      :desc "org-zotxt-insert-selected"
      ;; use <quote> in in case it pollute balanced brackets
      "C-c <quote> <quote>" (cmd!! #'org-zotxt-insert-reference-link '(4))
      :desc "org-zotxt-copy-attachment-path"
      "C-c <quote> c" #'org-zotxt-copy-attachment-path)
#+end_src

open attachment with point at arxiv link
- [[https://emacs.stackexchange.com/a/38297][Get description of an org-mode link - Emacs Stack Exchange]]
#+begin_src emacs-lisp
(defun org-zotxt-open-arxiv-attachment ()
  "open attachment from arxiv link, by zotxt"
  (interactive)
  (let* ((link (org-element-context))
         (desc (buffer-substring-no-properties (org-element-property :contents-begin link)
                                               (org-element-property :contents-end link))))
     (org-zotxt-insert-reference-link)))
#+end_src

**** insert arxiv links
#+begin_src emacs-lisp
(defvar rx-arxiv-regexp
  (rx (= 4 num) "." (= 5 num))
  "Regular expression for arxiv id.")

(defun org-insert-arxiv-link ()
  "Insert arxiv link with arxiv id as description."
  (interactive)
  (let* ((ring (current-kill 0))
         (id (if (string-match rx-arxiv-regexp ring)
                 (match-string 0 ring)
               (read-string "Input arxiv id:"))))
    (insert " ")
    (org-insert-link nil (concat "https://arxiv.org/abs/" id) id)))
#+end_src

*** Format
format org-src
#+begin_src emacs-lisp
(map! :after org :map evil-org-mode-map
  :n "g Q" #'+format:region)
#+end_src

org-format
#+begin_src emacs-lisp
(use-package org-format
  :defer 10
  ;; dawn lazy load
  ;; :commands (apheleia-format-org-buffer)
  :init
  (add-to-list 'load-path (expand-file-name "org-format" org-directory)))
#+end_src

Local org extensions
#+begin_src emacs-lisp
(load! "lisp/org-babel-inline-results")
#+end_src

#+begin_src emacs-lisp
(cl-defun apheleia-format-org-buffer
    (&key buffer scratch callback &allow-other-keys)
  "Copy BUFFER to SCRATCH, then format scratch, then call CALLBACK."
  ;; ugly implement!
  (with-current-buffer scratch
    ;; FIXME so many local value to copy
    (let ((buffer-file-name (buffer-local-value 'buffer-file-name buffer))
          (org-format-ignore-link (buffer-local-value 'org-format-ignore-link buffer))
          (org-format-keep-empty-below-heading (buffer-local-value 'org-format-keep-empty-below-heading buffer)))
      (org-format-buffer))
    (funcall callback)))

(after! org
  (set-formatter! 'orgfmt #'apheleia-format-org-buffer :modes '(org-mode)))
#+end_src

*** Others
Do not track remote files in org-persist; it may reconnect to TRAMP hosts on exit.
#+begin_src emacs-lisp
(after! org-persist
  (setq org-persist-remote-files nil))
#+end_src

[[kbd:SPC s b]] should work as expected
- [[https://github.com/doomemacs/doomemacs/issues/6478#issuecomment-1328110153][doomemacs/doomemacs#6478 `evil-ex-search` skips matches in folded regions (in...)]]

revert native ~org-cycle~ style, see [[doom-modules:lang/org/README.org]]
#+begin_src emacs-lisp
(after! evil-org
  (remove-hook 'org-tab-first-hook #'+org-cycle-only-current-subtree-h))
#+end_src

[[https://github.com/hlissner/doom-emacs/issues/5436][hlissner/doom-emacs#5436 org-src-window-setup not working correctly]]
#+begin_src emacs-lisp
(after! org-src
  (setq org-src-window-setup 'reorganize-frame)
  (set-popup-rule! "^\\*Org Src" :ignore t))
#+end_src

#+begin_src emacs-lisp
(after! org
  (setq org-archive-location ".bak/%s_archive::"))
#+end_src

Avoid lengthy title
#+begin_src emacs-lisp
(after! org-cliplink
  (setq org-cliplink-max-length 40))
#+end_src

#+begin_src emacs-lisp :tangle packages.el
(package! org-modern-indent
  :recipe (:type git :host github :repo "jdtsmith/org-modern-indent"))
#+end_src

#+begin_src emacs-lisp
(use-package org-modern-indent
  :config ; add late to hook
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90))
#+end_src

Smaller org src-block font size, more contents displayed.
#+begin_src emacs-lisp
(add-hook! org-mode
  (set-face-attribute 'org-code nil :height 0.8)
  ;; max height of org-indent and org-code will be applied
  (set-face-attribute 'org-indent nil :height 0.8))
#+end_src

** python
#+begin_src toml
[python]
packages=[
    "ty", "python-black", "python-isort",
    "python-nose", "python-pytest",
    "tree-sitter-python"
]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref lang
(python +lsp +pyright +tree-sitter)
#+end_src

[[https://github.com/doomemacs/doomemacs/issues/3171][doomemacs/doomemacs#3171 if: Need a v...]]
#+begin_src emacs-lisp
(with-eval-after-load 'ob-core
  (setq org-babel-default-header-args:jupyter-python
        '((:kernel . "python3"))))
#+end_src

Emacs 30.2 on Arch once had a distro packaging issue that broke tree-sitter
font-lock queries in =*-ts-mode=. See the [[https://emacs-china.org/t/ts-mode/31236][Emacs China discussion]].

** sh
#+begin_src toml
[sh]
packages=["shellcheck-bin", "bash-language-server", "shfmt"]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref lang
(sh +fish +lsp +powershell)
#+end_src

fish shell ligatures
#+begin_src emacs-lisp
(after! fish-mode
  (set-ligatures! 'fish-mode
    :def "function"
    :return "return"
    :and "&&"
    :or "||"
    :not "not"
    :true "true"
    :false "false"
    :for "for"))
#+end_src

Here is for [[var:shell-file-name]], will remove ~doom doctor~'s complain.
#+begin_src emacs-lisp
(setq shell-file-name (executable-find "bash"))
(setq-default vterm-shell "/bin/fish")
(setq-default explicit-shell-file-name "/bin/fish")
#+end_src

** yaml
#+begin_src toml
[yaml]
packages=["yaml-language-server"]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref lang
(yaml +lsp)
#+end_src

** wolfram
#+begin_src toml
[wolfram]
enabled="not is_wsl"
packages=["mathematica"]
#+end_src

#+begin_src emacs-lisp :tangle packages.el
(package! wolfram-mode
  :recipe (:local-repo "~/lib/wolfram-mode/"))
#+end_src

#+begin_src emacs-lisp
(use-package! wolfram-mode
  :defer t
  :config
  (with-eval-after-load 'dirvish
    (add-to-list 'dirvish-binary-exts "nb")))
#+end_src

wolfram-format
#+begin_src emacs-lisp
(after! apheleia
  (load "~/lib/wolframFormatter/wolfram-format.el"))
#+end_src
Note that =apheleia-formatter= not work well with org-src block, turn
=org-indent-mode= off and then run [[kbd:g Q]] and then turn on =org-indent-mode=.

*** ligatures
#+begin_src emacs-lisp
(after! (wolfram-mode ligature)
  (set-ligatures! 'wolfram-mode
    :and "&&"
    :or "||"
    :not "!"
    :null "None"
    :true "True"
    :false "False"))
#+end_src

*** =lsp-wl= with =eglot=
#+begin_src bash :tangle no
WLPATH="~/.local/lib/lsp-wl/"
[[ -d "$WLPATH" ]] || git clone https://github.com/kenkangxgwe/lsp-wl.git "$WLPATH"
#+end_src

#+begin_src Wolfram-Language :tangle no
PacletInstall["CodeParser"]
PacletInstall["CodeInspector"]
PacletInstall["ZeroMQLink"] (* 1.2.6+ *)
#+end_src

=eglot= is far faster than =LSP=!
- [[https://github.com/kenkangxgwe/lsp-wl/wiki#eglot][Home · kenkangxgwe/lsp-wl Wiki · GitHub]]
#+begin_src emacs-lisp
(let ((wlserver (expand-file-name "~/.local/lib/lsp-wl/init.wls")))
  (when (and (file-exists-p wlserver) (executable-find "wolframscript"))
    (with-eval-after-load 'eglot
      (add-to-list 'eglot-server-programs
                   `(wolfram-mode . ("wolframscript" "-f" ,wlserver
                                     "--tcp-server" :autoport))))))
#+end_src
Completion seems not work with =12.3=.

*** wolfram in jupyter
#+begin_src emacs-lisp
(add-to-list '+my/jupyter-langs "Wolfram-Language")

(after! org-src
  (add-to-list 'org-src-lang-modes '("Wolfram-Language" . wolfram))
  (setq org-babel-default-header-args:Wolfram-Language
        '((:kernel . "wolframforjupyter")
          (:async . "yes")
          (:results . "scalar"))))
#+end_src

#+begin_src emacs-lisp
(add-to-list '+org-babel-native-async-langs 'Wolfram-Language)
#+end_src

=<>= in =Wolfram= org-src break parentheses match.
#+begin_src emacs-lisp :tangle no
(defun +my/remove-angle-brackets-from-syntax ()
  (modify-syntax-entry ?< "." (syntax-table))  ;; Treat < as punctuation
  (modify-syntax-entry ?> "." (syntax-table))) ;; Treat > as punctuation

(add-hook 'org-mode-hook #'+my/remove-angle-brackets-from-syntax)
#+end_src

*** snippets
#+begin_src emacs-lisp
(after! (wolfram-mode yasnippet)
  (let ((key-templates '()))
    (dolist (key wolfram-structure-keywords)
      (push `(,key ,(format "(* ::%s:: *)\n(*$1*)\n\n" key)) key-templates))
    (yas-define-snippets 'wolfram-mode key-templates)))
#+end_src

** typst
#+begin_src toml
["typst-mode"]
packages=[
    "typst",
    "tree-sitter-typst-git", # tree sitter grammar for typst, demand by typst-ts-mode
    "tinymist" # language server
    # "typst-lsp-bin" # alternative language server
]
#+end_src

#+begin_src emacs-lisp :tangle packages.el
(package! typst-ts-mode
  :recipe (:host codeberg
           :repo "meow_king/typst-ts-mode"
           :files (:defaults "*.el")))
#+end_src

#+begin_src emacs-lisp
(use-package! typst-ts-mode
  :mode ("\\.typ\\'")
  :custom
  ;; (typst-ts-watch-options "--open")
  (typst-ts-mode-grammar-location (expand-file-name "tree-sitter/libtree-sitter-typst.so" user-emacs-directory))
  (typst-ts-mode-enable-raw-blocks-highlight t)
  :config
  (setq typst-ts-mode-indent-offset 2)
  (keymap-set typst-ts-mode-map "C-c C-c" #'typst-ts-tmenu))
#+end_src

use =pdf-tools= to preview
#+begin_src emacs-lisp
(after! typst-ts-mode
  (setq typst-ts-compile-hide-compilation-buffer-if-success nil)
  (setq typst-ts-preview-function
        (lambda (pdf)
          (let ((buffer (find-file-noselect pdf)))
            (display-buffer buffer)
            (with-current-buffer buffer
              (when (derived-mode-p 'pdf-view-mode)
                (pdf-view-revert-buffer nil t)))))))
#+end_src

language server
#+begin_src emacs-lisp
(with-eval-after-load 'eglot
  (with-eval-after-load 'typst-ts-mode
    (add-to-list 'eglot-server-programs
                 `((typst-ts-mode) .
                   ,(eglot-alternatives `(,typst-ts-lsp-download-path
                                          "tinymist"
                                          "typst-lsp"))))))
#+end_src
more configuration on [[https://myriad-dreamin.github.io/tinymist//frontend/emacs.html][Tinymist Docs]]

#+begin_src emacs-lisp
(defun +my/tex2typ-region-to-kill-ring (beg end)
  "Convert selected LaTeX math to Typst and copy result to kill-ring."
  (interactive "r")
  (let* ((text (buffer-substring-no-properties beg end))
         (cmd (format "tex2typ %s" (shell-quote-argument text)))
         (output (string-trim (shell-command-to-string cmd))))
    (kill-new output)
    (message "Copied Typst: %s" output)))

(map! :v "C-c t" #'+my/tex2typ-region-to-kill-ring)
#+end_src

** COMMENT julia
#+begin_src toml
[julia]
packages=["julia-bin"]
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref lang
(julia +lsp +tree-sitter)
#+end_src

If we want table output without ~:results output~
#+begin_src julia :tangle no
import Pkg; Pkg.add("DataFrames")
import Pkg; Pkg.add("CSV")
#+end_src

also one need to enable [[doom-module::lang ess]], see
[[https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-julia.html][Julia Code Blocks in Babel]]

** kdl
#+begin_src emacs-lisp :tangle packages.el
(package! kdl-mode)
#+end_src

#+begin_src emacs-lisp
(use-package kdl-mode)
#+end_src

* Email
** mu4e
#+begin_src toml
[mu4e]
packages=[
    "isync",
    "mu",
    "pass",
    "msmtp"
    #"imagemagick"
]
#+end_src

Example for initialing =mu= and =mbsync=
#+begin_src fish :tangle no
mkdir -p ~/.mail/$mailname
mu init --maildir=~/.mail --my-address=...@...
mu index
mbsync -c ~/.config/isync/$mbsyncrc -V -a
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref email
(mu4e +gmail +org)
#+end_src

#+begin_src emacs-lisp :tangle no
(set-popup-rule! "^\\*mu4e-\\(main\\|headers\\)\\*" :ignore t)
#+end_src

#+begin_src emacs-lisp
(setq mu4e-update-interval 300)
(after! mu4e
  (setq mu4e-split-view 'vertical
        mu4e-change-filenames-when-moving t
        mu4e-attachment-dir "~/Downloads"
        ;; every new email composition gets its own frame!
        mu4e-compose-in-new-frame t
        mu4e-use-fancy-chars t))
#+end_src

send email by =msmtp=, see [[file:~/.config/msmtp/config]]
#+begin_src emacs-lisp
(after! mu4e
  (setq sendmail-program (executable-find "msmtp")
        send-mail-function #'smtpmail-send-it
        message-sendmail-f-is-evil t
        message-sendmail-extra-arguments '("--read-envelope-from")
        message-send-mail-function #'message-send-mail-with-sendmail))
#+end_src

private variables ~mu4e-get-mail-command~ and ~mu4e-contexts~
#+begin_src emacs-lisp
(after! mu4e
  (load-in-doom-dir "private/mu4e.el"))
#+end_src

* App
** rss
#+begin_src emacs-lisp :tangle no :noweb-ref app
(rss +org)
#+end_src

[[https://pragmaticemacs.wordpress.com/2016/08/17/read-your-rss-feeds-in-emacs-with-elfeed/][Read your RSS feeds in emacs with elfeed | Pragmatic Emacs]]
#+begin_src emacs-lisp
(after! elfeed
  (add-hook! 'elfeed-search-mode-hook 'elfeed-update)
  (setq elfeed-db-directory (concat (getenv "NCDIR") "elfeed/db/")
        elfeed-enclosure-default-dir (concat (getenv "NCDIR") "elfeed/enclosures/")
        ;; elfeed-search-filter "@1-month-ago +unread"
        rmh-elfeed-org-files (list (expand-file-name "elfeed.org" org-directory))))

(map! :leader
       (:prefix "o"
        :desc "elfeed"    "e" #'elfeed))

(after! elfeed-goodies
  (setq elfeed-goodies/entry-pane-size 0.5))
#+end_src

** everywhere
#+begin_src emacs-lisp :tangle no :noweb-ref app
everywhere
#+end_src

#+begin_src toml
[everywhere]
packages=[
    "xclip",
    "xdotool",
    "xorg-xprop",
    "xorg-xwininfo"
]
#+end_src

** screenshot
#+begin_src emacs-lisp :tangle packages.el
(package! screenshot
  :recipe (:host github :repo "yangsheng6810/screenshot"))
#+end_src

#+begin_src emacs-lisp
(use-package! screenshot
  :commands screenshot
  :init
  (map! (:leader :prefix "o"
         :desc "sreenshot within emacs" "S" #'screenshot)))
#+end_src

Allow attach the screenshot.
#+begin_src emacs-lisp
(after! screenshot
  (screenshot--def-action
   "attach"
   (set-process-sentinel
    ;; NOTE feh not transparent well when shadow is included
    (start-process "feh" nil "feh"
                   "--class=attached_window"
                   screenshot--tmp-file)
    (lambda (process event) (delete-file screenshot--tmp-file))))

  (transient-append-suffix 'screenshot-transient '(-1 1)
    '("a" "Attach" screenshot-attach)))
#+end_src

=alias --save convert magick= in fish shell to suppress the warning
#+begin_quote
WARNING: The convert command is deprecated in IMv7, use "magick" instead of
"convert" or "magick convert"
#+end_quote

*Issues*
1. Region not correctly selected in =vterm= buffer
2. When select in visual line mode, newline not stripped

** COMMENT shrface
#+begin_src emacs-lisp :tangle packages.el
(package! shrface)
#+end_src

#+begin_src emacs-lisp
(use-package! shrface
  :hook eww-after-render-hook
  :commands request-url-as-org
  :config
  (shrface-basic)
  (shrface-trial)
  (shrface-default-keybindings) ; setup default keybindings
  (setq shrface-href-versatile t)

  (defun request-url-as-org (url)
    (interactive "sRequest url: ")
    (require 'shrface)
    (require 'request)
    (setq-local shrface-request-url url)
    (request url
      :parser 'buffer-string
      :headers '(("User-Agent" . "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"))
      :sync nil
      :success (cl-function
                (lambda (&key data &allow-other-keys)
                  (shrface-html-export-as-org data))))))
#+end_src

** COMMENT telega
#+begin_src emacs-lisp :tangle packages.el
(package! telega)
#+end_src

#+begin_src toml :tangle packages.toml
[telega]
packages=["docker"]
#+end_src

#+begin_src shell :tangle no
docker pull zevlg/telega-server:latest
#+end_src

#+begin_src emacs-lisp
(use-package! telega
  :commands telega
  :init
  (setq telega-directory (expand-file-name "~/.local/share/telega"))
  :config
  (setq telega-use-docker t)
  ;; ("\\.pdf\\'" . default) is already member in `org-file-apps'
  ;; Use "xdg-open" to open files by default
  (setcdr (assq t org-file-apps-gnu) 'browse-url-xdg-open)
  (setq telega-open-file-function 'org-open-file)
  (setq telega-proxies '((:server "127.0.0.1" :port 1089 :enable t
                          :type (:@type "proxyTypeSocks5")))))
  ;; (setq telega-server-libs-prefix "/usr"))
#+end_src
