#!/bin/bash

ARGS=(-c -s utility)

if "$(dirname "$0")"/daemon.sh; then
    ARGS+=(-n)
fi
emacsclient "${ARGS[@]}" \
    -e "(progn (setq-local default-directory \"${1:-$HOME}\") (+vterm/here t))" \
    -F "((width . 120) (height . 40))"
